
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - data/*.dvc

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo $ARTIFACTS_DESTINATION > .env
    echo $AZURE_STORAGE_CONNECTION_STRING >> .env
    echo $TRACKING_URI >> .env
  displayName: '.env file creation'


- bash: |
    snap install --classic dvc
    dvc
  displayName: 'Run a one-line script'