FROM python:3

RUN pip3 install mlflow azure-storage-blob

CMD mlflow server --backend-store-uri=sqlite:///mlrunsdb15.db --artifacts-destination=$ARTIFACTS_DESTINATION --default-artifact-root=$ARTIFACTS_DESTINATION --serve-artifacts --host 0.0.0.0 --port 5001
