FROM continuumio/miniconda3

WORKDIR /app
COPY environment.yaml ./

RUN conda update --name base conda
RUN conda env create --file environment.yaml

COPY . .

ENTRYPOINT ["conda", "run", "--name", "asi3", "python", "2_drift_detection.py"]
