version: '3.4'

services:
  drift:
    build:
      context: .
      dockerfile: Dockerfile.drift
    depends_on:
      - mlflow
    environment:
      - TRACKING_URI=http://mlflow:5001
    volumes:
      - ./mlruns:/app/mlruns

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    environment:
      - ARTIFACTS_DESTINATION=file:/app/mlruns
    ports:
      - 5001:5001
    volumes:
      - ./db/mlrunsdb15.db:/app/mlrunsdb15.db
      - ./mlruns:/app/mlruns

